[pytest]
addopts = -v -s --tb=short
;testpaths = 10_lesson
;python_files = test_*.py *_test.py
;python_classes = Test
;python_functions = test_*
#python_files = test_*.py *_test.py
#python_classes = Test* *Test *Suite
#python_classes = *suites *test
#python_files = *auto.py
#python_functions = *zero*
#python_functions = assert_*
#python_files = *suites.py *auto.py
#python_files = *ya.py
#python_files = test_01_form.py
;               test_02_calc.py
;               test_03_shop.py
python_files = Allure-Swag-Labs_auto_test.py
               Allure-Slow-Calculator_auto_test.py
#markers =
    ; positive_test: "только позитивные тесты"
    ; negative_test: "негативные тесты (проверка обработки ошибок)"
    ; auth_test:     "тесты на авторизацию"
    ; smoke: "дымовые тесты (быстрая проверка основных функций)"
    ; regression: "регрессионные тесты"
#python_functions = test_sum_positive
#python_functions = test_*
#testpaths = tests/
#log_cli = true
#log_cli_level = INFO
